# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CleanRxGithub' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'RxCocoa', '~> 4.0'
  pod 'GithubDomain', :path => '../lib/domain/GithubDomain'
  pod 'GithubNetwork', :path => '../lib/utility/GithubNetwork'
  pod 'GithubNetworkPlatform', :path => '../lib/platform/GithubNetworkPlatform'

end
